### ISSUE TITLE
Plugin is not working with latest Nemisys

### ISSUE THREAD

**Issue by MasterLuke117** [SupremeMortal/DNSForwarder#1]
```> 12:44:52 [ALERT] java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
at com.github.suprememortal.dnsforwarder.DNSForwarder.onEnable(DNSForwarder.java:31)
at org.itxtech.nemisys.plugin.PluginBase.setEnabled(PluginBase.java:75)
at org.itxtech.nemisys.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:120)
at org.itxtech.nemisys.plugin.PluginManager.enablePlugin(PluginManager.java:448)
at org.itxtech.nemisys.Server.enablePlugin(Server.java:299)
at org.itxtech.nemisys.Server.lambda$enablePlugins$1(Server.java:291)
at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
at org.itxtech.nemisys.Server.enablePlugins(Server.java:289)
at org.itxtech.nemisys.Server.<init>(Server.java:187)
at org.itxtech.nemisys.Nemisys.main(Nemisys.java:53)
> 12:44:52 [INFO] Disabling DNSForwarder v1.0.0```

**Comment by MasterLuke117** [comment]
My error,  don't forget the ":" between the domain name and the server disc. in the config!!
